package com.stocks.livermor.strategy.book;

import com.stocks.livermor.entity.Record;
import com.stocks.livermor.excel.ExcelWriter;
import com.stocks.technical.core.db.dao.CompanyDao;
import com.stocks.technical.core.db.entity.Candle;
import org.junit.Before;
import org.junit.Test;

import java.util.Comparator;
import java.util.List;

import static com.stocks.livermor.Constants.NULL_DATE;
import static com.stocks.livermor.Constants.Rule.*;
import static com.stocks.livermor.entity.State.*;
import static com.stocks.livermor.strategy.book.CheckingMechanism.*;

public class GazpTest {

    @Before
    public void init() {
        clear();
        Record firstNoDate = newRecord(130.29, DOWN_TREND, true);
        firstNoDate.setDate(NULL_DATE);
        Record secondNoDate = newRecord(138.7, NATURAL_RALLY, true);
        secondNoDate.setDate(NULL_DATE);
        addToRecordHolder(firstNoDate);
        addToRecordHolder(secondNoDate);
    }


    @Test
    public void test() throws Exception {
        firstQuarter();
        secondQuarter();
        thirdQuarter();
        fourthQuarter();
        allQuarters2016();

        List<Candle> candles = filter2016(new CompanyDao().getByName("GAZP.ME").getCandles());
        candles.sort(Comparator.comparing(Candle::getDate));

        for (Candle candle : candles) {
            Record record = new Record(candle.getDate().getTime(), candle.getClose().doubleValue());
            processWithNoCheck(record);
        }


        new ExcelWriter().createTable("GAZP", getRecordsHolder());
    }

    private void allQuarters2016() {
        processAndCheckNext(134.91, NONE, null, false);
        processAndCheckNext(136.45, NONE, null, false);
        processAndCheckNext(135.94, NONE, null, false);
        processAndCheckNext(131.38, DOWN_TREND, _11b, false);
        processAndCheckNext(133.54, NONE, null, false);
        processAndCheckNext(131.3, DOWN_TREND, _12_down, false);
        processAndCheckNext(130.86, DOWN_TREND, _12_down, false);
        processAndCheckNext(125.1, DOWN_TREND, _12_down, false);
        processAndCheckNext(124.6, DOWN_TREND, _12_down, true);
        processAndCheckNext(125.98, NONE, null, false);
        processAndCheckNext(125.83, NONE, null, false);
        processAndCheckNext(127.75, NATURAL_RALLY, _6c, false);
        processAndCheckNext(132.4, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(133.0, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(131.89, NONE, null, false);
        processAndCheckNext(134.0, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(136.5, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(136.6, NATURAL_RALLY, _12_rally, true);
        processAndCheckNext(133.9, NONE, null, false);
        processAndCheckNext(132.5, NATURAL_REACTION, _6b, false);
        processAndCheckNext(131.01, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(135.07, SECONDARY_RALLY, _6g, false);
        processAndCheckNext(134.43, NONE, null, false);
        processAndCheckNext(133.5, NONE, null, false);
        processAndCheckNext(132.7, NONE, null, false);
        processAndCheckNext(133.03, NONE, null, false);
        processAndCheckNext(130.49, NATURAL_REACTION, _6b, false);
        processAndCheckNext(131.3, NONE, null, false);
        processAndCheckNext(133.43, SECONDARY_RALLY, _6g, false);
        processAndCheckNext(135.85, SECONDARY_RALLY, _12_secondary_rally, false);
        processAndCheckNext(137.1, NATURAL_RALLY, _6g3, false);
        processAndCheckNext(138.0, UPPER_TREND, _5a, false);
        processAndCheckNext(136.9, NONE, null, false);
        processAndCheckNext(136.59, NONE, null, false);
        processAndCheckNext(139.9, UPPER_TREND, _12_upper, false);
        processAndCheckNext(137.15, NONE, null, false);
        processAndCheckNext(137.97, NONE, null, false);
        processAndCheckNext(138.67, NONE, null, false);
        processAndCheckNext(141.4, UPPER_TREND, _12_upper, false);
        processAndCheckNext(142.0, UPPER_TREND, _12_upper, false);
        processAndCheckNext(140.14, NONE, null, false);
        processAndCheckNext(144.5, UPPER_TREND, _12_upper, false);
        processAndCheckNext(146.16, UPPER_TREND, _12_upper, false);
        processAndCheckNext(150.15, UPPER_TREND, _12_upper, true);
        processAndCheckNext(147.43, NONE, null, false);
        processAndCheckNext(146.94, NATURAL_REACTION, _6a, false);
        processAndCheckNext(144.3, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(143.2, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(142.54, NATURAL_REACTION, _12_reaction, true);
        processAndCheckNext(144.75, NONE, null, false);
        processAndCheckNext(147.27, NATURAL_RALLY, _6d, false);
        processAndCheckNext(150.65, UPPER_TREND, _6d3, true);
        processAndCheckNext(149.9, NONE, null, false);
        processAndCheckNext(149.62, NONE, null, false);
        processAndCheckNext(146.0, SECONDARY_REACTION, _6aa, false);
        processAndCheckNext(145.8, SECONDARY_REACTION, _12_secondary_reaction, false);
        processAndCheckNext(146.04, NONE, null, false);
        processAndCheckNext(145.1, SECONDARY_REACTION, _12_secondary_reaction, false);
        processAndCheckNext(144.7, SECONDARY_REACTION, _12_secondary_reaction, false);
        processAndCheckNext(147.8, NATURAL_RALLY, _6d, false);
        processAndCheckNext(147.75, NONE, null, false);
        processAndCheckNext(147.2, NONE, null, false);
        processAndCheckNext(146.38, NONE, null, false);
        processAndCheckNext(144.34, SECONDARY_REACTION, _6h, false);
        processAndCheckNext(144.2, SECONDARY_REACTION, _12_secondary_reaction, false);
        processAndCheckNext(143.89, SECONDARY_REACTION, _12_secondary_reaction, false);
        processAndCheckNext(145.7, NONE, null, false);
        processAndCheckNext(147.3, SECONDARY_RALLY, _6g, false);
        processAndCheckNext(148.9, NATURAL_RALLY, _6g3, false);
        processAndCheckNext(153.12, UPPER_TREND, _6d3, true);
        processAndCheckNext(150.43, NONE, null, false);
        processAndCheckNext(147.99, NATURAL_REACTION, _6a, false);
        processAndCheckNext(146.3, NATURAL_REACTION, _12_reaction, true);
        processAndCheckNext(155.95, UPPER_TREND, _11a, false);
        processAndCheckNext(161.95, UPPER_TREND, _12_upper, false);
        processAndCheckNext(161.8, NONE, null, false);
        processAndCheckNext(161.2, NONE, null, false);
        processAndCheckNext(160.3, NONE, null, false);
        processAndCheckNext(163.0, UPPER_TREND, _12_upper, false);
        processAndCheckNext(160.99, NONE, null, false);
        processAndCheckNext(164.75, UPPER_TREND, _12_upper, false);
        processAndCheckNext(168.47, UPPER_TREND, _12_upper, true);
        processAndCheckNext(162.4, NATURAL_REACTION, _6a, false);
        processAndCheckNext(160.5, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(159.27, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(156.85, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(159.45, NONE, null, false);
        processAndCheckNext(159.03, NONE, null, false);
        processAndCheckNext(159.85, NONE, null, false);
        processAndCheckNext(158.07, NONE, null, false);
        processAndCheckNext(153.58, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(152.1, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(148.33, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(146.7, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(144.31, DOWN_TREND, _5b, true);
        processAndCheckNext(146.35, NONE, null, false);
        processAndCheckNext(146.55, NONE, null, false);
        processAndCheckNext(148.87, NATURAL_RALLY, _6c, false);
        processAndCheckNext(149.88, NATURAL_RALLY, _12_rally, true);
        processAndCheckNext(149.6, NONE, null, false);
        processAndCheckNext(145.5, NATURAL_REACTION, _6b, false);
        processAndCheckNext(144.7, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(144.0, DOWN_TREND, _6b3, false);
        processAndCheckNext(143.41, DOWN_TREND, _12_down, true);
        processAndCheckNext(146.4, SECONDARY_RALLY, _6cc, false);
        processAndCheckNext(147.75, SECONDARY_RALLY, _12_secondary_rally, false);
        processAndCheckNext(146.95, NONE, null, false);
        processAndCheckNext(144.98, NONE, null, false);
        processAndCheckNext(142.44, DOWN_TREND, _11b, false);
        processAndCheckNext(141.84, DOWN_TREND, _12_down, false);
        processAndCheckNext(141.57, DOWN_TREND, _12_down, false);
        processAndCheckNext(139.5, DOWN_TREND, _12_down, false);
        processAndCheckNext(139.32, DOWN_TREND, _12_down, true);
        processAndCheckNext(142.97, NATURAL_RALLY, _6c, false);
        processAndCheckNext(143.54, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(143.0, NONE, null, false);
        processAndCheckNext(144.2, NATURAL_RALLY, _12_rally, true);
        processAndCheckNext(141.25, NATURAL_REACTION, _6b, false);
        processAndCheckNext(138.52, DOWN_TREND, _6b3, true);
        processAndCheckNext(139.24, NONE, null, false);
        processAndCheckNext(140.0, NONE, null, false);
        processAndCheckNext(139.51, NONE, null, false);
        processAndCheckNext(140.05, NONE, null, false);
        processAndCheckNext(141.6, SECONDARY_RALLY, _6cc, false);
        processAndCheckNext(140.95, NONE, null, false);
        processAndCheckNext(139.99, NONE, null, false);
        processAndCheckNext(140.37, NONE, null, false);
        processAndCheckNext(140.27, NONE, null, false);
        processAndCheckNext(141.4, NONE, null, false);
        processAndCheckNext(142.12, SECONDARY_RALLY, _12_secondary_rally, false);
        processAndCheckNext(143.6, SECONDARY_RALLY, _12_secondary_rally, false);
        processAndCheckNext(144.2, SECONDARY_RALLY, _12_secondary_rally, false);
        processAndCheckNext(147.37, UPPER_TREND, _5a, true);
        processAndCheckNext(145.84, NONE, null, false);
        processAndCheckNext(139.48, NATURAL_REACTION, _6a, false);
        processAndCheckNext(139.26, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(140.1, NONE, null, false);
        processAndCheckNext(140.6, NONE, null, false);
        processAndCheckNext(140.7, NONE, null, false);
        processAndCheckNext(140.69, NONE, null, false);
        processAndCheckNext(139.5, NONE, null, false);
        processAndCheckNext(139.9, NONE, null, false);
        processAndCheckNext(137.3, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(136.93, DOWN_TREND, _6b3, false);
        processAndCheckNext(134.5, DOWN_TREND, _12_down, false);
        processAndCheckNext(134.04, DOWN_TREND, _12_down, true);
        processAndCheckNext(136.7, NONE, null, false);
        processAndCheckNext(135.5, NONE, null, false);
        processAndCheckNext(137.47, NATURAL_RALLY, _6c, false);
        processAndCheckNext(137.34, NONE, null, false);
        processAndCheckNext(137.4, NONE, null, false);
        processAndCheckNext(137.19, NONE, null, false);
        processAndCheckNext(137.83, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(138.0, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(137.99, NONE, null, false);
        processAndCheckNext(137.68, NONE, null, false);
        processAndCheckNext(138.4, NATURAL_RALLY, _12_rally, true);
        processAndCheckNext(136.8, NONE, null, false);
        processAndCheckNext(137.8, NONE, null, false);
        processAndCheckNext(137.37, NONE, null, false);
        processAndCheckNext(137.0, NONE, null, false);
        processAndCheckNext(135.42, NATURAL_REACTION, _6b, false);
        processAndCheckNext(136.2, NONE, null, false);
        processAndCheckNext(136.2, NONE, null, false);
        processAndCheckNext(135.59, NONE, null, false);
        processAndCheckNext(134.95, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(134.99, NONE, null, false);
        processAndCheckNext(135.55, NONE, null, false);
        processAndCheckNext(136.05, NONE, null, false);
        processAndCheckNext(141.4, UPPER_TREND, _5a, false);
        processAndCheckNext(143.08, UPPER_TREND, _12_upper, true);
        processAndCheckNext(141.45, NONE, null, false);
        processAndCheckNext(138.54, NATURAL_REACTION, _6a, false);
        processAndCheckNext(138.93, NONE, null, false);
        processAndCheckNext(138.45, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(139.35, NONE, null, false);
        processAndCheckNext(137.6, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(136.47, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(136.59, NONE, null, false);
        processAndCheckNext(137.0, NONE, null, false);
        processAndCheckNext(136.25, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(136.7, NONE, null, false);
        processAndCheckNext(136.7, NONE, null, false);
        processAndCheckNext(135.26, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(133.92, NATURAL_REACTION, _12_reaction, true);
        processAndCheckNext(134.09, NONE, null, false);
        processAndCheckNext(135.31, NONE, null, false);
        processAndCheckNext(134.9, NONE, null, false);
        processAndCheckNext(135.37, NONE, null, false);
//        processAndCheckNext(136.23, NONE, null, false);
//        processAndCheckNext(134.8, NONE, null, false);
//        processAndCheckNext(135.9, NONE, null, false);
//        processAndCheckNext(136.1, NONE, null, false);
        processAndCheckNext(139.1, NATURAL_RALLY, _6d, false);
        processAndCheckNext(138.98, NONE, null, false);
        processAndCheckNext(138.07, NONE, null, false);
        processAndCheckNext(137.47, NONE, null, false);
        processAndCheckNext(136.2, SECONDARY_REACTION, _6h, false);
        processAndCheckNext(135.57, SECONDARY_REACTION, _12_secondary_reaction, false);
        processAndCheckNext(135.81, NONE, null, false);
        processAndCheckNext(135.49, SECONDARY_REACTION, _12_secondary_reaction, false);
        processAndCheckNext(134.72, SECONDARY_REACTION, _12_secondary_reaction, false);
        processAndCheckNext(134.96, NONE, null, false);
        processAndCheckNext(135.05, NONE, null, false);
        processAndCheckNext(135.3, NONE, null, false);
        processAndCheckNext(135.32, NONE, null, false);
        processAndCheckNext(135.04, NONE, null, false);
        processAndCheckNext(135.0, NONE, null, false);
        processAndCheckNext(138.84, SECONDARY_RALLY, _6g, false);
        processAndCheckNext(141.98, NATURAL_RALLY, _6g3, false);
        processAndCheckNext(140.81, NONE, null, false);
        processAndCheckNext(139.9, NONE, null, false);
        processAndCheckNext(138.5, SECONDARY_REACTION, _6h, false);
        processAndCheckNext(139.32, NONE, null, false);
        processAndCheckNext(145.62, UPPER_TREND, _11a, false);
        processAndCheckNext(147.4, UPPER_TREND, _12_upper, false);
        processAndCheckNext(147.88, UPPER_TREND, _12_upper, false);
        processAndCheckNext(146.26, NONE, null, false);
        processAndCheckNext(145.9, NONE, null, false);
        processAndCheckNext(145.5, NONE, null, false);
        processAndCheckNext(147.7, NONE, null, false);
        processAndCheckNext(146.96, NONE, null, false);
        processAndCheckNext(149.6, UPPER_TREND, _12_upper, false);
        processAndCheckNext(150.0, UPPER_TREND, _12_upper, false);
        processAndCheckNext(149.49, NONE, null, false);
        processAndCheckNext(151.11, UPPER_TREND, _12_upper, false);
        processAndCheckNext(151.31, UPPER_TREND, _12_upper, true);
        processAndCheckNext(148.94, NONE, null, false);
        processAndCheckNext(147.75, NATURAL_REACTION, _6a, true);
        processAndCheckNext(148.8, NONE, null, false);
        processAndCheckNext(152.81, UPPER_TREND, _11a, false);
        processAndCheckNext(152.35, NONE, null, false);
        processAndCheckNext(153.78, UPPER_TREND, _12_upper, false);
        processAndCheckNext(151.5, NONE, null, false);
        processAndCheckNext(151.95, NONE, null, false);
        processAndCheckNext(153.05, NONE, null, false);
        processAndCheckNext(152.99, NONE, null, false);
        processAndCheckNext(158.63, UPPER_TREND, _12_upper, false);
        processAndCheckNext(158.95, UPPER_TREND, _12_upper, true);
        processAndCheckNext(157.2, NONE, null, false);
        processAndCheckNext(158.25, NONE, null, false);
        processAndCheckNext(156.2, NONE, null, false);
        processAndCheckNext(154.6, NATURAL_REACTION, _6a, false);
        processAndCheckNext(155.3, NONE, null, false);
        processAndCheckNext(153.06, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(150.27, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(149.05, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(148.95, NATURAL_REACTION, _12_reaction, true);
        processAndCheckNext(150.38, NONE, null, false);
        processAndCheckNext(151.0, NONE, null, false);
        processAndCheckNext(152.62, NATURAL_RALLY, _6d, false);
        processAndCheckNext(154.55, NATURAL_RALLY, _12_rally, false);
    }


    private void firstQuarter() {
        processAndCheckNext(130.31, NATURAL_REACTION, _6b, false);
        processAndCheckNext(133.95, SECONDARY_RALLY, _6g, false);
        processAndCheckNext(138.92, NATURAL_RALLY, _6g3, false);
        processAndCheckNext(146.46, UPPER_TREND, _5a, true);
        processAndCheckNext(141.7, NATURAL_REACTION, _6a, false);
        processAndCheckNext(140.22, NATURAL_REACTION, _12_reaction, true);
        processAndCheckNext(146.3, NATURAL_RALLY, _6d, false);
        processAndCheckNext(147.0, UPPER_TREND, _6d3, false);
        processAndCheckNext(149.6, UPPER_TREND, _12_upper, true);
        processAndCheckNext(145.75, NATURAL_REACTION, _6a, true);
        processAndCheckNext(148.8, NATURAL_RALLY, _6d, false);
        processAndCheckNext(151.5, UPPER_TREND, _6d3, false);
        processAndCheckNext(152.83, UPPER_TREND, _12_upper, true);
        processAndCheckNext(148.0, NATURAL_REACTION, _6a, false);
        processAndCheckNext(150.9, NONE, null, false);
        processAndCheckNext(147.7, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(145.0, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(143.82, DOWN_TREND, _5b, false);
        processAndCheckNext(138.18, DOWN_TREND, _12_down, true);
        processAndCheckNext(140.35, NONE, null, false);
        processAndCheckNext(142.6, NATURAL_RALLY, _6c, false);
        processAndCheckNext(147.6, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(151.6, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(149.3, NONE, null, false);
        processAndCheckNext(157.7, UPPER_TREND, _6d3, false);
        processAndCheckNext(162.4, UPPER_TREND, _12_upper, false);
        processAndCheckNext(163.0, UPPER_TREND, _12_upper, true);
        processAndCheckNext(158.0, NATURAL_REACTION, _6a, false);
        processAndCheckNext(154.99, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(150.7, NATURAL_REACTION, _12_reaction, true);
        processAndCheckNext(155.55, NATURAL_RALLY, _6d, false);
        processAndCheckNext(159.0, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(154.0, SECONDARY_REACTION, _6h, false);
        processAndCheckNext(152.12, SECONDARY_REACTION, _12_secondary_reaction, false);
        processAndCheckNext(148.05, DOWN_TREND, _5b, false);
        processAndCheckNext(145.99, DOWN_TREND, _12_down, false);
        processAndCheckNext(144.7, DOWN_TREND, _12_down, false);
        processAndCheckNext(141.8, DOWN_TREND, _12_down, false);
        processAndCheckNext(139.75, DOWN_TREND, _12_down, false);
        processAndCheckNext(139.7, DOWN_TREND, _12_down, false);
        processAndCheckNext(140.25, NONE, null, false);
        processAndCheckNext(136.81, DOWN_TREND, _12_down, false);
        processAndCheckNext(136.0, DOWN_TREND, _12_down, false);
        processAndCheckNext(134.61, DOWN_TREND, _12_down, false);
        processAndCheckNext(132.2, DOWN_TREND, _12_down, true);
        processAndCheckNext(134.88, NATURAL_RALLY, _6c, false);
        processAndCheckNext(137.0, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(138.9, NATURAL_RALLY, _12_rally, false);
    }

    private void secondQuarter() {
        processAndCheckNext(143.0, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(143.9, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(143.94, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(145.7, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(146.2, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(147.27, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(148.1, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(148.0, NONE, null, false);
        processAndCheckNext(148.8, NATURAL_RALLY, _12_rally, true);
        processAndCheckNext(144.4, NATURAL_REACTION, _6b, false);
        processAndCheckNext(150.1, NATURAL_RALLY, _6d, false);
        processAndCheckNext(152.4, UPPER_TREND, _5a, true);
        processAndCheckNext(149.3, NATURAL_REACTION, _6a, true);
        processAndCheckNext(153.96, UPPER_TREND, _11a, false);
        processAndCheckNext(155.35, UPPER_TREND, _12_upper, true);
        processAndCheckNext(150.8, NATURAL_REACTION, _6a, false);
        processAndCheckNext(150.15, NATURAL_REACTION, _12_reaction, true);
        processAndCheckNext(153.89, NATURAL_RALLY, _6d, false);
        processAndCheckNext(152.05, NONE, null, false);
        processAndCheckNext(152.79, NONE, null, false);
        processAndCheckNext(152.50, NONE, null, false);
        processAndCheckNext(153.50, NONE, null, false);
        processAndCheckNext(156.33, UPPER_TREND, _6d3, true);
        processAndCheckNext(155.25, NONE, null, false);
        processAndCheckNext(152.1, SECONDARY_REACTION, _6aa, false);
        processAndCheckNext(155.52, NATURAL_RALLY, _6d, false);
        processAndCheckNext(155.25, NONE, null, false);
        processAndCheckNext(151.74, SECONDARY_REACTION, _6h, false);
        processAndCheckNext(151.8, NONE, null, false);
        processAndCheckNext(152.98, NONE, null, false);
        processAndCheckNext(151.9, NONE, null, false);
        processAndCheckNext(149.85, NATURAL_REACTION, _6h3, false);
        processAndCheckNext(146.35, DOWN_TREND, _5b, false);
        processAndCheckNext(147.16, NONE, null, false);
        processAndCheckNext(148.8, NONE, null, false);
        processAndCheckNext(146.69, NONE, null, false);
        processAndCheckNext(145.25, DOWN_TREND, _12_down, false);
        processAndCheckNext(147.66, NONE, null, false);
        processAndCheckNext(146.11, NONE, null, false);
        processAndCheckNext(139.0, DOWN_TREND, _12_down, true);
        processAndCheckNext(139.4, NONE, null, false);
        processAndCheckNext(140.75, NONE, null, false);
        processAndCheckNext(140.71, NONE, null, false);
        processAndCheckNext(140.2, NONE, null, false);
        processAndCheckNext(142.4, NATURAL_RALLY, _6c, false);
        processAndCheckNext(142.66, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(146.17, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(145.6, NONE, null, false);
        processAndCheckNext(145.4, NONE, null, false);
        processAndCheckNext(144.95, NONE, null, false);
        processAndCheckNext(146.0, NONE, null, false);
        processAndCheckNext(147.6, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(147.15, NONE, null, false);
        processAndCheckNext(147.15, NONE, null, false);
        processAndCheckNext(148.5, NATURAL_RALLY, _12_rally, true);
        processAndCheckNext(146.25, NONE, null, false);
        processAndCheckNext(146.68, NONE, null, false);
        processAndCheckNext(143.7, NATURAL_REACTION, _6b, false);
        processAndCheckNext(145.18, NONE, null, false);
        processAndCheckNext(143.59, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(145.85, NONE, null, false);
    }

    private void thirdQuarter() {
        processAndCheckNext(145.5, NONE, null, false);
        processAndCheckNext(145.8, NONE, null, false);
        processAndCheckNext(144.33, NONE, null, false);
        processAndCheckNext(143.0, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(142.5, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(141.5, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(143.77, NONE, null, false);
        processAndCheckNext(143.9, NONE, null, false);
        processAndCheckNext(145.27, SECONDARY_RALLY, _6g, false);
        processAndCheckNext(146.5, SECONDARY_RALLY, _12_secondary_rally, false);
        processAndCheckNext(142.7, SECONDARY_REACTION, _6h, false);
        processAndCheckNext(144.2, NONE, null, false);
        processAndCheckNext(143.6, NONE, null, false);
        processAndCheckNext(141.78, SECONDARY_REACTION, _12_secondary_reaction, false);
        processAndCheckNext(141.41, NATURAL_REACTION, _6h3, false);
        processAndCheckNext(140.8, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(138.37, DOWN_TREND, _6b3, false);
        processAndCheckNext(136.41, DOWN_TREND, _12_down, false);
        processAndCheckNext(134.51, DOWN_TREND, _12_down, true);
        processAndCheckNext(135.05, NONE, null, false);
        processAndCheckNext(138.7, NATURAL_RALLY, _6c, false);
        processAndCheckNext(139.8, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(142.5, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(141.45, NONE, null, false);
        processAndCheckNext(141.89, NONE, null, false);
        processAndCheckNext(143.78, NATURAL_RALLY, _12_rally, true);
        // вообще по записям тут 140.88
        processAndCheckNext(140.79, NATURAL_REACTION, _6b, false);
        processAndCheckNext(141.34, NONE, null, false);
        processAndCheckNext(141.5, NONE, null, false);
        processAndCheckNext(141.97, NONE, null, false);
        processAndCheckNext(142.99, NONE, null, false);
        processAndCheckNext(143.7, SECONDARY_RALLY, _6g, false);
        processAndCheckNext(144.8, NATURAL_RALLY, _6g3, false);
        processAndCheckNext(144.25, NONE, null, false);
        processAndCheckNext(142.65, NONE, null, false);
        // вообще по записям тут 140.8 (но это ошибка)
        processAndCheckNext(140.78, NATURAL_REACTION, _6b, false);
        processAndCheckNext(142.64, NONE, null, false);
        processAndCheckNext(140.29, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(135.35, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(140.4, SECONDARY_RALLY, _6g, false);
        processAndCheckNext(140.51, SECONDARY_RALLY, _12_secondary_rally, false);
        processAndCheckNext(144.6, SECONDARY_RALLY, _12_secondary_rally, false);
        processAndCheckNext(146.6, UPPER_TREND, _5a, false);
        processAndCheckNext(148.19, UPPER_TREND, _12_upper, true);
        processAndCheckNext(144.5, NATURAL_REACTION, _6a, false);
        processAndCheckNext(142.57, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(145.3, NONE, null, false);
        processAndCheckNext(142.8, NONE, null, false);
        processAndCheckNext(141.67, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(143.21, NONE, null, false);
        processAndCheckNext(144.22, NONE, null, false);
        processAndCheckNext(142.99, NONE, null, false);
        processAndCheckNext(142.4, NONE, null, false);
        // and some more none here
        processAndCheckNext(139.5, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(139.45, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(136.4, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(134.3, NATURAL_REACTION, _12_reaction, false);

        processAndCheckNext(132.2, DOWN_TREND, _6b3, false);
        processAndCheckNext(133.85, NONE, null, false);
        processAndCheckNext(130.9, DOWN_TREND, _12_down, true);
        processAndCheckNext(133.2, NONE, null, false);
        processAndCheckNext(134.55, NATURAL_RALLY, _6c, true);
    }

    private void fourthQuarter() {
        processAndCheckNext(132.9, NONE, null, false);
        processAndCheckNext(131.5, NATURAL_REACTION, _6b, false);
        processAndCheckNext(136.8, UPPER_TREND, _5a, false);
        processAndCheckNext(137.87, UPPER_TREND, _12_upper, false);
        processAndCheckNext(140.0, UPPER_TREND, _12_upper, false);
        processAndCheckNext(139.8, NONE, null, false);
        processAndCheckNext(143.81, UPPER_TREND, _12_upper, true);
        processAndCheckNext(141.7, NONE, null, false);
        processAndCheckNext(141.8, NONE, null, false);
        processAndCheckNext(142.01, NONE, null, false);
        // and some more nones.
        processAndCheckNext(140.27, NATURAL_REACTION, _6a, false);
        processAndCheckNext(140.4, NONE, null, false);
        processAndCheckNext(139.49, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(139.25, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(138.94, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(138.5, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(138.5, NONE, null, false);
        processAndCheckNext(138.1, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(136.11, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(135.75, NATURAL_REACTION, _12_reaction, true);
        processAndCheckNext(137.8, NONE, null, false);
        processAndCheckNext(141.75, NATURAL_RALLY, _6d, false);
        processAndCheckNext(140.97, NONE, null, false);
        processAndCheckNext(137.75, SECONDARY_REACTION, _6h, false);
        processAndCheckNext(135.58, NATURAL_REACTION, _6h3, false);
        processAndCheckNext(135.0, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(136.6, NONE, null, false);
        processAndCheckNext(136.0, NONE, null, false);
        processAndCheckNext(137.21, NONE, null, false);
        processAndCheckNext(142.75, NATURAL_RALLY, _6d, false);
        processAndCheckNext(147.47, UPPER_TREND, _6d3, false);
        processAndCheckNext(147.5, UPPER_TREND, _12_upper, false);
        processAndCheckNext(148.05, UPPER_TREND, _12_upper, false);
        processAndCheckNext(152.0, UPPER_TREND, _12_upper, true);
        processAndCheckNext(145.65, NATURAL_REACTION, _6a, false);
        processAndCheckNext(143.99, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(143.2, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(140.65, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(138.0, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(137.42, NATURAL_REACTION, _12_reaction, false);
        processAndCheckNext(136.85, NATURAL_REACTION, _12_reaction, true);
        processAndCheckNext(140.0, NATURAL_RALLY, _6d, false);
        processAndCheckNext(137.7, NONE, null, false);
        processAndCheckNext(134.5, DOWN_TREND, _5b, false);
        processAndCheckNext(134.65, NONE, null, false);
        processAndCheckNext(135.81, NONE, null, false);
        processAndCheckNext(135.6, NONE, null, false);
        processAndCheckNext(133.8, DOWN_TREND, _12_down, false);
        processAndCheckNext(131.59, DOWN_TREND, _12_down, true);
        processAndCheckNext(134.4, NATURAL_RALLY, _6c, false);
        processAndCheckNext(134.5, NATURAL_RALLY, _12_rally, false);
        processAndCheckNext(137.9, NATURAL_RALLY, _12_rally, true);
        processAndCheckNext(132.25, NATURAL_REACTION, _6b, false);
        processAndCheckNext(131.5, DOWN_TREND, _6b3, true);
        processAndCheckNext(133.2, NONE, null, false);
        // по записям не так, Денис сказал что у него ошибка.
        processAndCheckNext(135.3, SECONDARY_RALLY, _6cc, false);
        processAndCheckNext(136.0, SECONDARY_RALLY, _12_secondary_rally, false);
        processAndCheckNext(134.48, NONE, null, false);
        processAndCheckNext(134.97, NONE, null, false);
        processAndCheckNext(137.49, SECONDARY_RALLY, _12_secondary_rally, false);
        processAndCheckNext(136.09, NONE, null, false);
    }


}
